### ISSUE TITLE
 field.config.displayModifier is not a function

### ISSUE THREAD

**Issue by DariusMontez** [sails-adminpanel/sails-adminpanel#1]
I have a model called Product that has several one-way associations. 
I am getting 
 ` field.config.displayModifier is not a function` 
when attempting to add a record via the Product panel page.

```js
// config/adminpanel.js

module.exports.adminpanel = {
  instances: {
    products: {
      title: 'Products',
      model: 'Product',
    },
  }
};
```

The final trace of the error:
```
sails-adminpanel\views\ejs\mixin\fields\inputAssociation.ejs:25
    23|         }
    24|         if (<%= field.config.displayModifier && typeof field.config.displayModifi
er === 'function' %>) {
 >> 25|             label = "<%= field.config.displayModifier(opt) %>"
    26|         } else {
    27|             label = "<%= opt[field.config.displayField] %>"
    28|         }

field.config.displayModifier is not a function
```

My model:

```
// Product.js

module.exports = {
  attributes: {

    code: { type: 'string' },

    properties: {
      model: 'Properties'
    },

    // ... more similar associations
  },
};
```

---
sails: 1.5.2
sails-adminpanel: 2.0.0-pre.13
Windows 10

**Comment by DariusMontez** [comment]
The issue is that both clauses of the if statement were being rendered. That means `field.config.displayModifier` is called even if it fails the function type test. The if statement should be encapsulated in `<% ... %>` so that only one clause is rendered to the resulting script file. 

Encapsulating the if statement eliminates the problem:
```js
<% if (field.config.displayModifier && typeof field.config.displayModifier === 'function') { %>
    label = "<%= field.config.displayModifier(opt) %>"
<% } else { %>
    label = "<%= opt[field.config.displayField] %>"
<% } %>
```

**Comment by serebriakov19** [comment]
Hello, DariusMontez, we've already solved this problem. Please check new version of adminpanel. Thank you for your comment
