### ISSUE TITLE
mixin/fields/inputAssociation: redeclatarion of selectedOption, label

### ISSUE THREAD

**Issue by DariusMontez** [sails-adminpanel/sails-adminpanel#2]
The variables `selectedOption` and `label` are declared in the window namespace, so each time a new widget is added after the first, those variables get redeclared and the widget isn't rendered.

This problem can be solved by placing the entire script inside an immediately executing anonymous function.
```js
<script>
(function() {
    let options<%=key%> = [];
    let selectedOption;
    let label;
...
})();
</script>
```

**Comment by serebriakov19** [comment]
Hello, DariusMontez, we have fixed this problem already by adding specific key at the end of each variable
