### ISSUE TITLE
Error when title is omitted

### ISSUE THREAD

**Issue by DariusMontez** [sails-adminpanel/sails-adminpanel#3]
The docs say the title should be taken from the key when omitted, but in my case it is causing an error instead.

My adminpanel config:
```js
module.exports.adminpanel = {
  models: {

    coatings: {
      // title: 'Coatings', // causes error when commented out
      model: 'Coating',
    },
}
```

Error trace:
```
Cannot read properties of undefined (reading 'replace')
at ...\sails-adminpanel\helper\menuHelper.js:171:39
at Array.forEach (<anonymous>)
at MenuHelper.getMenuItems (...\sails-adminpanel\helper\menuHelper.js:156:54)
...
```

Looking at menuHelper.js in `getMenuItems()` line 171:
```js
menus.push({
    link: MenuHelper.config.routePrefix + '/model/' + key,
    title: val.title,
    icon: val.icon || null,
    actions: val.tools || null,
    id: val.title.replace(" ", "_"),
    entityName: key
});
````

It appears the error is called when `val.title` is undefined and `val.title.replace()` is attempted

Sails: 1.5.2
Adminpanel: 2.2.2

**Comment by serebriakov19** [comment]
Hello, DariusMontez, thank you for your advice. We added possibility to omit model title. Use branch "staged" to have last updates that is not released in master branch
