### ISSUE TITLE
selectbox tries to store index instead of string value

### ISSUE THREAD

**Issue by DariusMontez** [sails-adminpanel/sails-adminpanel#4]
I have a string field named "status" defined with an `isIn` array in my model:

models/Job.js
```js
status: {
  type: 'string',
  isIn: ['estimate', 'active', 'completed' ],
},
```

The first problem is, I have to override the `isIn` field in my adminpanel config in order to get a selectbox in the edit page. Otherwise it is a basic text input field.

So now I have this, which looks good:

![image](https://user-images.githubusercontent.com/12874532/184382527-7782e29a-84bc-4a55-8553-c9344f287d47.png)

But saving the record fails

```
Invalid new record. Details: Could not use specified `status`. Violated one or more validation rules: • Value ('0') was not in the configured whitelist (estimate, active, completed)
```

Seems like the array index (0) is being stored instead of the string value (estimate).

Sails: 1.5.2
Adminpanel: 2.2.2

**Comment by xziy** [comment]
Just fixed it, please check in staged branch
